### ISSUE TITLE
Injected Element returns wrong parent

### ISSUE THREAD

**Issue by zewa666** [aurelia/templating-router#1]
I've tried to inject the Element to the Welcome-Page of the Skeleton-App in order to get the parent element.

````
export class Welcome{
    static inject() { return [Element]; }
  constructor(Element){
    this.element = Element;
  }

  attached() {
    console.log(this.element);
  }
}
````
but instead of route-view it returns the body tag

**Comment by EisenbergEffect** [comment]
Ok, unfortunately we won't be able to fix this. The reason is that there is no view at the time that the Welcome view model is instantiated, so it can't be pushed in. I think that's ok because you shouldn't be interacting with an html element directly in your view model. That's something you do in a behavior. Fortunately, it's very easy and you can export a behavior side-by-side with your view model allowing you to easily separate the view manipulation logic but still have collaboration. Let me show you what that would look like for the Welcome scenario:

#### welcome.js
```javascript
export class Welcome{
  constructor(){
    console.log('welcome');
  }

  someMethod(){
    console.log('some method');
  }
}

export class FooAttachedBehavior{
  static inject() { return [Element, Welcome]; }
  constructor(element, welcome){
    element.addEventListener('click', () => welcome.someMethod());
  }
}
```

#### welcome.html
```html
<template>
  <div foo></div>
</template>
```

So the general rule would be to only use Element injection with a behavior. But because of the powerful DI you can still communicate with your local behaviors. (BTW No need to import foo into the view...local behaviors are automatically imported.) This also lets lets you attach the behavior to precisely the element you want to capture.

Hopefully there won't be a lot of need to interact with the view directly, but if you need to its completely possible and you get some nice isolation by doing it this way without much additional work. The conventions make it really easy to create these local behaviors.

**Comment by tyrsius** [comment]
@EisenbergEffect In durandal you could get the view in the viewmodel in the `attached` event. Is a similiar event not available in Aurelia?

I know mucking with the view in the viewmodel is a bad practice, but losing the option seems strange. Sometimes we need to hack things quickly.

**Comment by EisenbergEffect** [comment]
So, there's no way to get the view from the constructor due to a dependency resolution issue when routing. We had to do this in order to solve a number of problems..some of which couldn't be fixed in Durandal 2.x. You can't get it from the attached callback either since I tried to make that act like the Web Components model. Also, with Aurelia, you don't have to have a single root element in your view, so it makes it tricky to know which element to injection in the case of a dynamic view.

However...

In the middle of this I forgot about a feature the I put in the binding system that's even better. You can add for references to individual elements to be set as properties on your view. It's like binding to an element. You do it like this:

```html
<div interesting-element.ref></div>
```

You use `.ref` as the command to get a reference to an element. The property will be named `interestingElement`.

That's how it works today, but I'm not particularly happy about it. I was thinking of just doing this instead:

```html
<div ref="interestingElement"></div>
```

I'd like something where the name doesn't have to get changed due to different rules in html vs. JS. Interestingly if you put a ref on a custom element, you wont' get the HTML element, you will actually get the class that has the behavior for that element, since it basically represents the custom API for that element. Sometimes you might specifically want its HTML element instead of its API though, so I thought you could do this to specify that.

```html
<custom-element ref="interestingElement:Element"></custom-element>
```

So, the first syntax is supported now, but I was thinking of switching it to the new one...actually already was playing with that locally. Any thoughts on this?

**Comment by tyrsius** [comment]
@EisenbergEffect I think that looks really good, but when does that property become available?

**Comment by EisenbergEffect** [comment]
It becomes available in the `bind` callback. The `attached` callback happens later, so it's available there as well.

**Comment by tyrsius** [comment]
@EisenbergEffect The only concern I have is with the inconsistent behavior between elements and custom elements. I see the value in getting the custom element class, but perhaps that should be bound with a different attribute so that `ref` always returns the element reference.

**Comment by EisenbergEffect** [comment]
Summary of callbacks:

```javascript
export class MyViewModel {
  constructor() { }
  bind() { }
  attached() {}
  detached() {}
  unbind() {}
}
```

If you are being managed by a router,  you also get: `canActivate`, `activate`, `canDeactivate` and `deactivate`.

**Comment by EisenbergEffect** [comment]
@tyrsius Recommendation?

**Comment by zewa666** [comment]
Tried it, really liked it, although I'd prefer the second syntax ref="..."

**Comment by tyrsius** [comment]
@EisenbergEffect perhaps `model`

**Comment by tyrsius** [comment]
@EisenbergEffect or `viewmodel-ref`

**Comment by zewa666** [comment]
sry maybe it sounds stupid, but why not return both? So ref would return an object with property Element and Model or call it whatever you want.

**Comment by EisenbergEffect** [comment]
What about `ref="name"` for the element ref and `ref="name:Behavior"` for the behavior instance ref?

**Comment by tyrsius** [comment]
what would `model` be for non-custom elements? `null`?
Are the classes backing custom elements commonly called `Behavior`? I thought Behavior referred to Atttached Behavior's specifically.

**Comment by EisenbergEffect** [comment]
In Aurelia CustomElement, AttachedBehavior and TemplateController all inherit from Behavior.

**Comment by zewa666** [comment]
@EisenbergEffect to make it more consistent how about
```ref="name:Element"``` and ```ref="name:Behavior"``` and ```ref="name"``` both, in case there is no Behavior then null/undefined

**Comment by tyrsius** [comment]
I'll have to adjust to that. I'd still prefer a separate attribute, like `behavior-ref="name"` to overloading `ref` with a new syntax.

**Comment by tyrsius** [comment]
Especially considered the case where I might want both, then the overloaded syntax gets in the way.
I also prefer two attributes to `ref="name"` returning both.

**Comment by EisenbergEffect** [comment]
I don't want it to return both. What about `ref` for element and `ref.view-model` to get the custom element's view-model? I thin behavior might be misleading because you can't actually get AttachedBehaviors this way since there might be more than one on an element.

**Comment by tyrsius** [comment]
That makes sense, I like it.

**Comment by EisenbergEffect** [comment]
I think so too. It's similar in concept to the way the other bindings work. So ref looks like a normal attribute and then we use .view-model to indicate some special processing.

**Comment by EisenbergEffect** [comment]
Not sure if it is obvious, but with this feature you can do things like this:

```html
<input type="text" ref="name">
${name.value}
```

I've got a scenario right now where I created a custom menu popup element but it needs a reference to the html element that should trigger the popup to display. So, I use this technique to pass the reference to the custom element. Looks like this:

```html
<template>
  <button class="icon filled list-1-1" ref="actionTrigger"></button>
  <action-menu actions.bind="actions" trigger.bind="actionTrigger"></action-menu>
</template>
```

See how the button has the ref on it and then the custom actions-menu has a trigger property that is bound to that? Fun stuff...

**Comment by tyrsius** [comment]
@EisenbergEffect is that happening because the `ref="actionTrigger"` creates the property on the viewmodel? That's so slick, I love it.

**Comment by EisenbergEffect** [comment]
Yes, it basically sets it as a property with that name on the view-model. So, it's a way for you to get access to it if needed in your VM but once it's in the execution context, you can then bind to it in the view as well.
