### ISSUE TITLE
How to access RouterViewLocator -- not exported in the built code?

### ISSUE THREAD

**Issue by kevmeister68** [aurelia/templating-router#127]
Having read about RouterViewLocator, we want to experiment with it in our application but the class is not exported in the built module.

My understanding is that we'd have to Dependency Inject the RouterViewLocator into our view-model, but I cannot import it from aurelia-templating-router.

Am I going about this the entirely wrong way, or is there an oversight to export that class in aurelia-templating-router.ts ?

**Comment by lrech** [comment]
As part of our experimenting we've updated aurelia-templating-router.ts to export `RouterViewLocator`. This has allowed us to access the `RouterViewLocator` from the injected `Container`. We then use `findNearest()` to get our `RouterView`.

Here's an example code snippet of our intended usage:

```
let routerViewLocator = this.container.get( RouterViewLocator );
let routerView: RouterView = await routerViewLocator.findNearest();
let element = routerView.element;
```

Is this an appropriate use of the `RouterViewLocator` if it were exported?

**Comment by bigopon** [comment]
@lrech the router view locator `findNearest` is a single use call (there's only a single locator for the whole application). How are you experiementing it? We can export it if that makes it easier to workaround in applications, though Im curios.

**Comment by lrech** [comment]
Hi @bigopon,
To further explain what we are trying to achieve by using the `RouterViewLocator` our scenario is this.

Our Dialog class (basically a View) will often not acquire its own element through `@inject()`, so we have been providing an appropriate element (the <router-view> element) to the Dialog that our events can use to perform tasks (a common one is for a whole-of-Dialog key-down handler).

In the version of Aurelia that we were using, even if a Dialog/View @inject’ed “Element”, the Element it would receive is the Body element of the document, so we did not want to use that.

Up to now (based on an older version of Aurelia) we were relying on Aurelia's dialog lifecycle to grab a reference to the router-view element (ie. using ref=”blah” on the router-view element) and have that element available to the Dialog by the time we hit the activate() function.

Since we're in the process of updating our Aurelia components to current version we've discovered we can no longer rely on the old sequence of lifecycle events. This left our Dialogs without an element to use by the time we reach the attached() function.

Our research led us to find the `RouterViewLocator` class and the `findNearest()` function. However we also discovered that the `RouterViewLocator` class isn't exported as part of the aurelia-templating-router, so there is no “key” we can pass to Container.get( ) to get it. We've updated the Aurelia source code locally to test our theory and it appears to be working for us. 

Hopefully the above explains why we are proposing the change to expose the `RouterViewLocator` via an export (and appropriate Typescript types).

Our proposed changes in src/aurelia-templating-router.ts are:

```
@@ -1,6 +1,6 @@
import { Router, AppRouter, RouteLoader } from 'aurelia-router';
import { TemplatingRouteLoader } from './route-loader';
-import { RouterView } from './router-view';
+import { RouterView, RouterViewLocator } from './router-view';
import { RouteHref } from './route-href';
import { IFrameworkConfiguration } from './interfaces';

@ -19,5 +19,6 @@ export function configure(config: IFrameworkConfiguration) {
export {
  TemplatingRouteLoader,
  RouterView,
+ RouterViewLocator,
  RouteHref
};
```

The build script took care of the rest, including an update to the .d.ts file.

Cheers,
Lou

**Comment by bigopon** [comment]
@lrech this module entry:
```ts
import { Router, AppRouter, RouteLoader } from 'aurelia-router';
import { TemplatingRouteLoader } from './route-loader';
import { RouterView } from './router-view';
import { RouteHref } from './route-href';
import { IFrameworkConfiguration } from './interfaces';

export function configure(config: IFrameworkConfiguration) {
  config
    .singleton(RouteLoader, TemplatingRouteLoader)
    .singleton(Router, AppRouter)
    .globalResources(
      RouterView,
      RouteHref
    );

  config.container.registerAlias(Router, AppRouter);
}
```

There are not a lot going on here. And the main thing is around this line
```ts
    .singleton(RouteLoader, TemplatingRouteLoader)
```
I think you can come with your custom plugin configure to register your own `TemplatingRouteLoader` like this:

```ts
// file: templating-router.ts
import { Router, AppRouter, RouteLoader } from 'aurelia-router';
import { RouteHref, RouterView } from 'aurelia-templating-router';
import { FrameworkConfiguration } from 'aurelia-framework';
import { MyAppTemplatingRouteLoader } from './my-app-route-loader';

export function configure(config: FrameworkConfiguration) {
  config
    .singleton(RouteLoader, MyAppTemplatingRouteLoader )
    .singleton(Router, AppRouter)
    .globalResources(
      RouterView,
      RouteHref
    );

  config.container.registerAlias(Router, AppRouter);
}
```

and in your `main.ts`:
```ts
// file: main.ts
aurelia.use.plugin(PLATFORM.moduleName('./templating-router'))

// or
aurelia.use.feature(PLATFORM.moduleName('./templating-router'))
```

---

That said, we probably will also be exporting the `TemplatingRouteLoader`.

**Comment by bigopon** [comment]
@lrech actually I read it wrong, it's the `RouteViewLocator`, sorry. And I meant we probably will be exporting that.

**Comment by lrech** [comment]
@bigopon, what are the next steps for this issue. I'm happy to submit a pull request for the export change. However the link to the CLA document appears to be broken [CLA](http://goo.gl/forms/dI8QDDSyKR) from Contributing document. Or I can attached the updated aurelia-templating-router.ts file here.

**Comment by bigopon** [comment]
@lrech I'll be making that chang, no worries. Since there' other updates needed as well.

**Comment by bigopon** [comment]
The `RouterViewLocator` has been exposed. In order to register application own implementation, do:
```ts
// main.js
import { RouterViewLocator } from 'aurelia-templating-router'

export function configure(aurelia) {
  ...
  aurelia.container.register(RouterViewLocator, MyRouterViewLocator)
}
```

The interface of any `RouterViewLocator` implementation should conform:
```ts
import { RouterView } from 'aurelia-templating-router';

interface IRouterViewLocator {
  findNearest(): Promise<RouterView>;
}
```
