### ISSUE TITLE
layout-view property of a <router-view> does not update when binding changes

### ISSUE THREAD

**Issue by toonevdb** [aurelia/templating-router#69]
**I'm submitting a bug report**

* **Library Version:**
1.2.0

**Please tell us about your environment:**
* **Operating System:**
Ubuntu 17.10

* **Node Version:**
8.7.0

* **NPM Version:**
5.4.2

* **JSPM OR Webpack AND Version**
JSPM 0.17.0-beta.47

* **Browser:**
all 

* **Language:**
all 

**Current behavior:**
It seems that the layout-view property of a router-view does not refresh its bindings after it is rendered. Updating the value of the bound variable doesn't do anything.

**Expected/desired behavior:**
If the value changes, the layout view should be changed and all descendant elements rerendered.

**Example**
I created a plunker at https://embed.plnkr.co/zoOfSKHJsAFAxD45jCyk/ demonstrating the problem. In app.js and app.html you will see a toggle button and function changing a bindable layout name. Pressing that button, changes the layout name which is reflected in the view but does not change the layout view. 

Maybe this isn't possible but the documentation states that the property is bindable (http://aurelia.io/docs/routing/configuration#layouts) so I would expect it to work :).

**Comment by Alexander-Taran** [comment]
Well reading the https://github.com/aurelia/templating-router/blob/master/src/router-view.js revealed that it is grabbed at the moment of processing navigation instruction.
have you tried navigating to another sub-route after?

as it is now - it definitely won't change on the fly.

it is `@bindable` yes.. to be able to get it from attribute on router-view.
can think of it as one-way.

don't think it was indented the other way

**Comment by davismj** [comment]
This is an important issue though. I kinda take offense to the layout feature because it didn't add any new functionality. It is essentially a glorified compose (see gist). However, it has created a whole set of new, less robust code that doesn't function as expected and is difficult to maintain.

Perhaps in 2.0 we can refactor the whole feature to keep the API but leverage compose under the hood.

Compose as layout gist:
https://gist.run/?id=f07255e6aa96d1962848d24d2d1ba2c1

**Comment by toonevdb** [comment]
@Alexander-Taran I tried a few different approaches.
I suspected that 2way binding wasn't supported after a while :)

@davismj Can't remember why I switched to using compose exactly but your gist is exactly how I'm handling my layout logic now. Binding a view model to the compose element. Allows for layout specific functions in the view model too.

I use a router pipeline step for authorization and can't use `return next.cancel(new Redirect(loginRoute))` for example. It won't update the view model binding if I listen to router navigation events for example. I have to use `location.href = loginRoute`. 

For our application it isn't a big deal since we only use a blank layout for our login page and most people probably won't need such dynamic refreshing.

**Comment by Alexander-Taran** [comment]
@davismj & @EisenbergEffect 
It is most definitely the case for cookbook
If one could solve it with compose but didn't think of it.. It can be explained in a recipe.
@toonevdb could you come up with a short guide on the subject?

Using compose for layout.

use case
how to solve with compose
how it compares with layout feature
and PR it here https://github.com/aurelia-contrib/aurelia-getting-started/tree/master/guides

**Comment by davismj** [comment]
Can you brief me on why people wanted layouts in the first place? I can do a write up but I have no idea how to motivate it.

**Comment by Alexander-Taran** [comment]
I can only speak for myself..
For the app I was building at the time I wanted to reuse some logic
We had a master-detail scenario (navigation pane + content) 
We had several "screens" with that scenario
One of the cases begged for navigation pane to be collapsible like solution explorer in VS or any other app when you can "unpin" something to occupy less real estate.

We thought that it would benefit us to abstract the common logic away.. and since we never thought of compose as a solution.. we were happy to see layout feature implemented..
although it did not support viewModel as we thought..
and when it did we already moved on


![image](https://user-images.githubusercontent.com/1029452/38303477-d7492bc4-380e-11e8-9358-8a5156f473e1.png)

we wanted to abstract the button in layout to collapse (hide) left slot. and be able to reuse that across several routes

**Comment by toonevdb** [comment]
The benefit in my case was not having to write `if.bind="layout != 'blank'"` in every top level custom element we have (like breadcrumbs, menu-primary, menu-secondary, etc).
